# Generated by Django 5.2.13 on 2026-05-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('specie', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
