# Generated by Django 5.2.13 on 2026-05-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantsApp', '0002_colors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
    ]
