# Generated by Django 5.2.13 on 2026-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantsApp', '0003_rename_colors_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yop', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('fuelType', models.CharField(choices=[('D', 'Diesel'), ('P', 'Petrol')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
